apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: sztzixl1m-nodejs 
  janus-idp.io/tekton: sztzixl1m-nodejs
  backstage.io/kubernetes-id: sztzixl1m-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: sztzixl1m-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  